<?php
/**
 * Genesis Framework.
 *
 * WARNING: This file is part of the core Genesis Framework. DO NOT edit this file under any circumstances.
 * Please do all modifications in the form of a child theme.
 *
 * @package Genesis\Templates
 * @author  The Customize Windows
 * @license GPL-2.0+
 * @link    https://thecustomizewindows.com/
 */

//* Template Name: Sitemap

//* Remove standard post content output
remove_action( 'genesis_post_content', 'genesis_do_post_content' );
remove_action( 'genesis_entry_content', 'genesis_do_post_content' );

add_action( 'genesis_entry_content', 'genesis_page_archive_content' );
add_action( 'genesis_post_content', 'genesis_page_archive_content' );
/**
 * This function outputs sitemap-esque columns displaying all pages,
 * categories, authors, monthly archives, and recent posts.
 *
 * @since 1.6
 */
function genesis_page_archive_content() { ?>

<?php echo genesis_html5() ? '<article>' : '<div>'; ?>
<style>
.thecustomizewindows-custom{
margin-bottom: 1em !important;
margin-top: 1em !important;
column-count: 3;
column-gap: 10 px;
column-rule-color: #0274BE;
column-rule-style: outset;
column-rule-width: 1px;
box-sizing: border-box;
display: block;
line-height: 1.5;
}
@media only screen and (max-width: 1139px) {
.thecustomizewindows-custom {
column-count: 2;}
}
@media only screen and (max-width: 480px) {
.thecustomizewindows-custom {
column-count: 1;}
}
</style>
       	<h2><?php _e( 'Monthly:', 'genesis' ); ?></h2>
<hr>
<div class="thecustomizewindows-custom">
       	<ul>
       		<?php wp_get_archives( 'type=monthly' ); ?>
       	</ul>
</div>
<hr>
       	<h4><?php _e( 'Recent 100 Posts:', 'genesis' ); ?></h4>
       	<ul>
       		<?php wp_get_archives( 'type=postbypost&limit=100' ); ?>
       	</ul>
<hr>
<div class="thecustomizewindows-custom">
       		<h4><?php _e( 'Pages:', 'genesis' ); ?></h4>
       	<ul>
       		<?php wp_list_pages( 'title_li=' ); ?>
       	</ul>
</div>
<hr>
       	<h4><?php _e( 'Categories:', 'genesis' ); ?></h4>
       	<ul>
       		<?php wp_list_categories( 'sort_column=name&title_li=' ); ?>
       	</ul>

       	<h4><?php _e( 'Authors:', 'genesis' ); ?></h4>
       	<ul>
       		<?php wp_list_authors( 'exclude_admin=0&optioncount=1' ); ?>
       	</ul>

<h4><?php _e("Site Feeds", "genesis"); ?></h4>
<ul>
<li><a href="<?php bloginfo('rss2_url'); ?>"><?php _e("Main RSS Feed", "genesis"); ?></a></li>
</ul>

<p style="text-align: right;"><span style="color: #999;">dEVELOPED by <a title="The Customize Windows" href="https://thecustomizewindows.com/" target="_blank">The Customize Windows</a></span></p>

<?php
echo genesis_html5() ? '</article>' : '</div>';
}

genesis();
